[package]
name = "rust-mcp"
version = "0.1.0"
edition = "2024"

[dependencies]
rmcp = { version = "0.8.5", features = ["transport-io", "macros"] }
rmcp-macros = "0.17.0"
schemars = "1.2.1"
serde = "1.0.228"
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["full"] }
