[package]
name = "rust-mcp-agentcore"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.7"
rmcp = { version = "0.8.5", features = [
    "transport-streamable-http-server",
    "macros",
] }
rmcp-macros = "0.9.0"
schemars = "1.1.0"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }
