[package]
name = "rust-mcp-agentcore"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
rmcp = { version = "0.8.4", features = [
    "transport-streamable-http-server",
    "macros",
] }
rmcp-macros = "0.8.5"
schemars = "1.0.5"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }
