[package]
name = "rust_dynamodb"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-config = { version = "1.8.11", features = ["rustls"] }
aws-sdk-dynamodb = "1.100.0"
reqwest = { version = "0.12.24", default-features = false, features = [
  "gzip",
  "http2",
  "rustls-tls",
] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
