[package]
name = "rust-lambda-chrome"
version = "0.1.0"
edition = "2021"

[dependencies]
fast_html2md = "0.0.55"
headless_chrome = "1.0.20"

lambda_runtime = "1.0.2"
serde = "1"
tokio = { version = "1", features = ["macros"] }
tracing = "0.1.44"
