[package]
name = "rust-aws"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-config = "1.8.11"
aws-sdk-sts = "1.94.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
